In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("clean_train.csv")
df["Assortment"] = df["Assortment"].apply(lambda x: [int(i) for i in x[1:-1].split(",")])
df["Probability"] = df["Probability"].apply(lambda x: [float(i) for i in x[1:-1].split(",")])
df

Assortment  \
0                     [0, 2]   
1                [0, 22, 27]   
2             [0, 7, 17, 22]   
3         [0, 17, 7, 21, 14]   
4      [0, 7, 2, 25, 30, 13]   
...                      ...   
2495                 [0, 13]   
2496             [0, 23, 17]   
2497         [0, 11, 10, 29]   
2498      [0, 16, 25, 13, 1]   
2499  [0, 22, 10, 15, 4, 17]   

                                            Probability  
0               [0.6171762553809882, 0.382823744619012]  
1     [0.49010203287014026, 0.3856208197783525, 0.12...  
2     [0.17383055343275639, 0.44812960860117884, 0.2...  
3     [0.1338762504510885, 0.1933610050447225, 0.365...  
4     [0.09520137647807961, 0.4258881190119289, 0.02...  
...                                                 ...  
2495          [0.37037705537265336, 0.6296229446273469]  
2496  [0.25241095695520893, 0.10976818151988744, 0.6...  
2497  [0.13702096921422796, 0.17458857209162085, 0.6...  
2498  [0.167781680054737, 0.29015312192773385, 0.148...  
2499  [0.0784077752482451, 0.03763805678406826, 0.51...  

[2500 rows x 2 columns]

In [ ]:
# Feature of the 30 products, Cores, Frequency,TDP, Price
ind = range(1,31)
x1 = [8 if 6<=i and i<=15 else 4 for i in ind]
x2 = [2.9 if 6<=i and i<=20 else 2.2 if 26<=i else 3.2 for i in ind]
x3 = [95 if i<=5 or (11<=i and i<=15) and i<=20 else 135 if 26<=i else 60 for i in ind]
x4 = [3000-300*((i-1)%5) for i in ind]
x= np.array([x1,x2,x3,x4]).T

<h3> Appended Table

In [ ]:
#Appending infinity to x and 0 to y for non-exist product to make them into a consistent 6x4 matrix
for i in range (2500):
        while len(df.Probability[i])<6:
            df.Probability[i].append(float('0'))
for i in range (2500):
        while len(df.Assortment[i])<6:
            df.Assortment[i].append(float('-inf'))
df

Assortment  \
0      [0, 2, -inf, -inf, -inf, -inf]   
1       [0, 22, 27, -inf, -inf, -inf]   
2          [0, 7, 17, 22, -inf, -inf]   
3            [0, 17, 7, 21, 14, -inf]   
4               [0, 7, 2, 25, 30, 13]   
...                               ...   
2495  [0, 13, -inf, -inf, -inf, -inf]   
2496    [0, 23, 17, -inf, -inf, -inf]   
2497      [0, 11, 10, 29, -inf, -inf]   
2498         [0, 16, 25, 13, 1, -inf]   
2499           [0, 22, 10, 15, 4, 17]   

                                            Probability  
0     [0.6171762553809882, 0.382823744619012, 0.0, 0...  
1     [0.49010203287014026, 0.3856208197783525, 0.12...  
2     [0.17383055343275639, 0.44812960860117884, 0.2...  
3     [0.1338762504510885, 0.1933610050447225, 0.365...  
4     [0.09520137647807961, 0.4258881190119289, 0.02...  
...                                                 ...  
2495  [0.37037705537265336, 0.6296229446273469, 0.0,...  
2496  [0.25241095695520893, 0.10976818151988744, 0.6...  
2497  [0.13702096921422796, 0.17458857209162085, 0.6...  
2498  [0.167781680054737, 0.29015312192773385, 0.148...  
2499  [0.0784077752482451, 0.03763805678406826, 0.51...  

[2500 rows x 2 columns]

In [ ]:
# replace products in assortment with their corresponding features
x_list=[]
X =df['Assortment']
for sub_list in X:
    for value in sub_list:
        x_list.append(value)

x_fea=[]
for i in x_list:
    if i == float('-inf'):
        x_fea.append(np.array([int(-1e9),int(-1e9),int(-1e9),int(-1e9)]))
    elif i == float('0'):
         x_fea.append(np.array([int(0),int(0),int(0),int(0)]))
    else:
        ind = int(i-1)
        x_fea.append(x[ind])
x_fea= np.array(x_fea)
x_fea

array([[ 0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00],
       [ 4.0e+00,  3.2e+00,  9.5e+01,  2.7e+03],
       [-1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09],
       ...,
       [ 8.0e+00,  2.9e+00,  9.5e+01,  1.8e+03],
       [ 4.0e+00,  3.2e+00,  9.5e+01,  2.1e+03],
       [ 4.0e+00,  2.9e+00,  6.0e+01,  2.7e+03]])

In [ ]:
# convert them into matrix such that 2500 of 24x1  assortment matrix
arr = np.array(x_fea).reshape((2500, 6, 4))
x_fea_mat = np.array(arr.tolist())
x_fea_mat = np.reshape(x_fea_mat, (2500, -1))
x_fea_mat=np.array(x_fea_mat)
x_fea_mat[0]

array([ 0.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,  4.0e+00,  3.2e+00,
        9.5e+01,  2.7e+03, -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09,
       -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09,
       -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09, -1.0e+09])

In [ ]:
# convert y into matrix such that 2500 of 6x1 assortment matrix

y_list=[]
Y =df['Probability']
for sub_list in Y:
    for value in sub_list:
        y_list.append(value)
arr = np.array(y_list).reshape((2500, 6, 1))

y_mat = arr.tolist()
y_mat=np.array(y_mat)
y_mat = y_mat.reshape(-1, y_mat.shape[-1])
y_mat=y_mat.reshape(-1, 6)
y_mat[0]

array([0.61717626, 0.38282374, 0.        , 0.        , 0.        ,
       0.        ])

<h3> 0.8 training version

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

# X:x_fea_mat, assortment in feature forms
# y:y_mat, probability of the products

X_train, X_test, y_train, y_test = train_test_split(x_fea_mat, y_mat, test_size=0.2, random_state=42)
regressor = GradientBoostingRegressor(alpha=0.001, learning_rate=0.1, max_depth=6, n_estimators=200,random_state=42)

# Use multi-target regression to allow multi-target
multioutput_regressor = MultiOutputRegressor(regressor)
multioutput_regressor.fit(X_train, y_train)
y_pred=multioutput_regressor.predict(X_test)


#Softmax function on y_pred: Element is transformed to a value between 0 and 1, representing a probability distribution
y_pred = np.exp(y_pred) / np.sum(np.exp(y_pred))

# set pred_y (Probability) to 0 when the 4 X features are all -inf
for i in range(len(X_test)):
    for a in range(0, 23, 4):
        change_y = True
        if all(x == -1.0e+09 for x in X_test[i][a:a+4]) and change_y:
            y_pred[i][a//4] = 0  
            change_y = False  
        elif not all(x == -1.0e+09 for x in X_test[i][a:a+4]):
            change_y = True  

# Normalise them to make them sum up be 1 -> fulfill probability condition          
y_pred = np.apply_along_axis(lambda x: x/np.sum(x), 1, y_pred)

# Check 
MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_pred,y_test)
RMSE = np.sqrt(MSE)
MSE, MAE, RMSE

(0.012747302314598826, 0.07726193544834971, 0.11290395172268695)

<h3> 10 fold version

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import KFold

# X:x_fea_mat, assortment in feature forms
# y:y_mat, probability of the products

def KFold_MSE():
    kf = KFold(n_splits=10)
    MSE=[]
    MAE =[]
    for train_index, test_index in kf.split(x_fea_mat):
        X_train = x_fea_mat[train_index]
        X_test=x_fea_mat[test_index]
        
        y_train = y_mat[train_index]
        y_test=y_mat[test_index]
        
        regressor = GradientBoostingRegressor(alpha=0.001, learning_rate=0.1, max_depth=6, n_estimators=200,random_state=42)
       
        # Use multi-target regression to allow multi-target
        multioutput_regressor = MultiOutputRegressor(regressor)
        multioutput_regressor.fit(X_train, y_train)
        y_pred=multioutput_regressor.predict(X_test)
        #Softmax function on y_pred: Element is transformed to a value between 0 and 1, representing a probability distribution
        y_pred = np.exp(y_pred) / np.sum(np.exp(y_pred))
        
        # set predicted y (Probability) to 0 when the x is -inf
        for i in range(len(X_test)):
            for a in range(0, 23, 4):
                change_y = True
                if all(x == -1.0e+09 for x in X_test[i][a:a+4]) and change_y:
                    y_pred[i][a//4] = 0  # change y once for every set of 4 -1.0e+09 values
                    change_y = False  # toggle the flag
                elif not all(x == -1.0e+09 for x in X_test[i][a:a+4]):
                    change_y = True  # reset flag

        # normalise them to make them sum up be 1 -> fulfill probability condition          
        y_pred = np.apply_along_axis(lambda x: x/np.sum(x), 1, y_pred)    
        MSE.append(mean_squared_error(y_pred,y_test))
        MAE.append(mean_absolute_error(y_pred,y_test))
    return np.mean(MSE), np.mean(MAE), np.sqrt(np.mean(MSE))


KFold_MSE()

(0.01273896571743503, 0.07638125439781182, 0.11286702670592076)

In [ ]:
MSE=[KFold_MSE()][0][0]
MAE=[KFold_MSE()][0][1]
RMSE=[KFold_MSE()][0][2]
print (f'MSE:{MSE}, MAE:{MAE}, RMSE:{RMSE}')

MSE:0.01273896571743503, MAE:0.07638125439781182, RMSE:0.11286702670592076
